### ISSUE TITLE
Add styling options for decorations

### ISSUE THREAD

**Issue by 1Computer1** [1Computer1/errata#1]
There should be options for enabling/disabling the various decorations and whatnot.

* [x] `styleEnableDecorations` to enable/disable the underlines, connectors, and labels on source lines.
* [x] `styleEnableLinePrefix` to enable/disable the vertical bar and line number behind each line.
* [x] `styleEnableHook` (in `PointerStyle`) to enable/disable the "hook" for labels that drop down, and start labels directly under the connector when disabled.
* [x] ~`styleCompact` to enable/disable the padding lines above and below the source code, but only when there is no underline/label below e.g. combined with `styleEnableDecorations = False`.~ Implemented with `stylePaddingTop` and `stylePaddingBottom`.

**Comment by novara754** [comment]
Will work on it; expect a PR soon!

**Comment by 1Computer1** [comment]
`styleEnableHook` implemented, other three are too much effort IMO. If someone would like them, let me know!
