### ISSUE TITLE
Consider adding to Stackage

### ISSUE THREAD

**Issue by ejconlon** [1Computer1/errata#7]
Hello! This is a great library. I use it in my `simple-parser` library to show pretty errors ([example](https://github.com/ejconlon/simple-parser/blob/master/src/SimpleParser/Interactive.hs#L38)). Would you consider adding it to Stackage? I can make the PR in the [stackage repo](https://github.com/commercialhaskell/stackage) if you +1 it. Typically the burden as a library author is just getting an issue notification if your package falls out of the package set due to constraint failures. I doubt this will happen with the few common dependencies you have. Thanks!

**Comment by 1Computer1** [comment]
Hey there! I'll add the next release (soon™) to Stackage.

**Comment by 1Computer1** [comment]
PR has been made!
